use sakila;

-- List the number of films per category.

SELECT c.name AS 'Category Name',
    COUNT(f.film_id) AS 'Number of Films'
FROM film_category AS fc
JOIN film AS f
ON fc.film_id = f.film_id
JOIN category AS c 
ON fc.category_id = c.category_id
GROUP BY c.name;

-- Retrieve the store ID, city, and country for each store.

select s.store_id, c.city_id, cy.country_id
from store as s
join address as a
on s.address_id = a.address_id
join city as c
on c.city_id = a.city_id
join country as cy
on cy.country_id = c.country_id;


-- Calculate the total revenue generated by each store in dollars.

SELECT s.store_id, 
       SUM(p.amount) AS total_revenue
FROM store AS s
JOIN staff AS st ON s.store_id = st.store_id
JOIN payment AS p ON st.staff_id = p.staff_id
GROUP BY s.store_id;


-- Determine the average running time of films for each category.

SELECT c.name AS category_name,
       AVG(f.length) AS average_running_time
FROM film_category AS fc
JOIN film AS f ON fc.film_id = f.film_id
JOIN category AS c ON fc.category_id = c.category_id
GROUP BY c.name;